### PR TITLE
Updated package and tests for Mongoose 4.x

### LINKED ISSUE #6: Moongoose 4.0
Mongoose 4.0 is now the latest version. 

Can the dependencies be updated to require mongoose "4.x" instead of "3.x"?

### PR DESCRIPTION
**Pull request by TylerLH**
This PR should resolve #6 -- all tests are passing.

### CODE REVIEW

**Comment by paulcsmith** [comment]
Thanks for this! I know a lot of people wanted it. I'll take a look and merge it in if I don't see any issues

**Comment by paulcsmith** [comment]
Also if you haven't already can you bump the version to 0.2.0 please?

**Comment by sheppyc** [comment]
@paulcsmith Could this be merged in? And possibly have the node_modules folder removed - or is that required?

**Comment by TylerLH** [comment]
Bumped the version, and removed node_modules. Not sure why it made it in there -- we have node_modules in the .gitignore.

**Comment by paulcsmith** [comment]
Thanks a ton @TylerLH!

**Comment by paulcsmith** [comment]
@TylerLH @sheppyc I merged this in, but I seem to be getting errors when running the tests. Can you pull in master and confirm the tests pass? Maybe it's something in my environment? I haven't used node or mongoose in a long time so it could be my machine.

**Comment by paulcsmith** [comment]
I get these 3 failures:

```
  1) Currency Type the returned object from requiring mongoose-currency should have a loadType method:
     TypeError: Property 'a' of object #<Assertion> is not a function
      at Context.<anonymous> (test/test.js:16:41)

  2) Currency Type mongoose.Schema.Types.Currency should be a function:
     TypeError: Property 'a' of object #<Assertion> is not a function
      at Context.<anonymous> (test/test.js:31:48)

  3) Currency Type mongoose.Schema.Types.Currency should have a method called cast:
     TypeError: Property 'a' of object #<Assertion> is not a function
      at Context.<anonymous> (test/test.js:34:63)
```

**Comment by TylerLH** [comment]
Interesting! I do see the errors after cloning from master, and also in my fork. Funny, definitely had a passing suite of tests when I created the PR. Will take a deeper look ASAP.

**Comment by paulcsmith** [comment]
Thank you :) I'll publish to npm once the tests pass. I really appreciate your help and I'm sure others using this library do as well

**Comment by TylerLH** [comment]
Just submitted PR #8 which fixes the test suite. The package.json file didn't have a should.js version pinned, so after removing node_modules and performing a fresh install of deps, there was a later version being used than what I originally fixed the tests in. (Usage of should.be changed between the 2 versions)

**Comment by paulcsmith** [comment]
@TylerLH @sheppyc This has been pushed to npm. Thanks!

**Comment by sheppyc** [comment]
Thanks guys - appreciate the responsiveness - it's a great module ! :)

**Pull request merged**
